apiVersion: v1
kind: Pod
metadata:
  name: ipfs
  labels:
    name: ipfs
spec:
  volumes:
    - name: ipfs-storage
      persistentVolumeClaim:
        claimName: ipfs-data
  containers:
  - name: ipfs
    image: docker.io/ipfs/kubo:latest
    env:
    - name: IPFS_SWARM_KEY
      valueFrom:
        secretKeyRef:
          name: ipfs-secret
          key: swarmKey
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 4001
    volumeMounts:
    - name: ipfs-storage
      mountPath: /data/ipfs

---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-service
spec:
  selector:
    name: ipfs
  ports:
  - port: 4001
    targetPort:  4001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-data
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Secret
metadata:
  name: ipfs-secret
type: Opaque
data:
  swarmKey: |
    L2tleS9zd2FybS9wc2svMS4wLjAvCi9iYXNlMTYvCjRmNGY4OTRjOGFkNmQwMzM1NWFiYjRkMWIx
    NGYwODA5MGFlYmY5ZjcwYzVjNTliZjBhOWFkNzZmNDFlZjQ2N2UK
